<?php

return [
    'services' => [
        'Rank Boosting',
        'Placement Matches',
        'Radiant Boost',
        'Ranked Wins',
    ],

    'ranks' => [
        'Iron I',
        'Iron II',
        'Iron III',
        'Bronze I',
        'Bronze II',
        'Bronze III',
        'Silver I',
        'Silver II',
        'Silver III',
        'Gold I',
        'Gold II',
        'Gold III',
        'Platinum I',
        'Platinum II',
        'Platinum III',
        'Diamond I',
        'Diamond II',
        'Diamond III',
        'Ascendant I',
        'Ascendant II',
        'Ascendant III',
        'Immortal I',
        'Immortal II',
        'Immortal III',
        'Radiant',
    ],

    'default_current_rank' => 'Gold III',
    'default_desired_rank' => 'Platinum III',

    'regions' => ['NA', 'EU', 'APAC', 'LATAM'],
    'platforms' => ['PC', 'Console'],
    'boost_modes' => ['Account Shared', 'Duo / Self-Play'],
    'average_rr_options' => ['16 OR LOWER', '18 OR LOWER', '20 OR MORE'],

    'addons' => [
        'offline-mode' => [
            'label' => 'Offline Mode',
            'description' => 'Keeps the session discreet by having the booster play with an offline presence whenever possible.',
            'icon' => 'assets/addons/offline-mode.png',
            'sort_order' => 1,
            'aliases' => ['Appear offline', 'Appear offline (Free)', 'Offline mode'],
        ],
        'specific-agents' => [
            'label' => 'Specific Agents',
            'description' => 'Locks the run to the agents you want prioritized so the order stays aligned with your pool and comfort picks.',
            'icon' => 'assets/addons/specific_agents.png',
            'sort_order' => 2,
            'aliases' => ['Specific agents', 'Specific Agents (Free)', 'Specific agents (+10%)'],
        ],
        'one-trick-agent' => [
            'label' => 'One-Trick Agent',
            'description' => 'Focuses the boost around one main agent to protect consistency, comfort, and account identity.',
            'icon' => 'assets/addons/one_trick.png',
            'sort_order' => 3,
            'aliases' => ['One-trick', 'One-trick focus', 'One-trick focus (+15%)', 'ONE TRICK PONY', 'ONE TRICK PONY (+15%)'],
        ],
        'solo-queue-only' => [
            'label' => 'Solo-Queue Only',
            'description' => 'Prevents party queue boosting and keeps the order limited to solo-queue matches only.',
            'icon' => 'assets/addons/solo_only.png',
            'sort_order' => 4,
            'aliases' => ['Solo queue', 'Solo queue only', 'Solo queue only (+50%)', 'SOLO ONLY', 'SOLO ONLY (+50%)'],
        ],
        'no-5-stack' => [
            'label' => 'No 5-Stack',
            'description' => 'Avoids 5-stack lobbies to keep match conditions closer to standard ranked conditions.',
            'icon' => 'assets/addons/no_5_stack.png',
            'sort_order' => 5,
            'aliases' => ['No 5-stack', 'No 5-stack (+30%)', 'No 5-stack (+40%)', 'NO 5 STACK', 'NO 5 STACK (+30%)'],
        ],
        'bonus-win' => [
            'label' => 'Bonus Win',
            'description' => 'Adds an extra win target buffer when you want a little more margin on the final delivery.',
            'icon' => 'assets/addons/bonus_win.png',
            'sort_order' => 6,
            'aliases' => ['Bonus win', 'Bonus win (+1)'],
        ],
        'streaming' => [
            'label' => 'Streaming',
            'description' => 'Keeps the order stream-friendly so you can request visibility or content-safe handling during the run.',
            'icon' => 'assets/addons/Live_Streaming.png',
            'sort_order' => 7,
            'aliases' => ['Streaming', 'STREAMING (+5$ or 15%)', 'Streaming (+5$ or 15%)'],
        ],
        'express-order' => [
            'label' => 'Express Order',
            'description' => 'Pushes the order higher in the execution queue for faster handling and shorter delivery windows.',
            'icon' => 'assets/addons/Express_Order.png',
            'sort_order' => 8,
            'aliases' => ['Express', 'Express order', 'Express Order (+30%)', 'EXPRESS ORDER (+30%)'],
        ],
        'normalize-scores' => [
            'label' => 'Normalize Scores',
            'description' => 'Aims for cleaner, more natural-looking scorelines instead of forcing the fastest possible result every match.',
            'icon' => 'assets/addons/normalize_scores.png',
            'sort_order' => 9,
            'aliases' => ['Normalize RR', 'Normalize scores', 'Normalize scores (+50%)', 'NORMALIZE SCORES (+50%)'],
        ],
        'record-clips' => [
            'label' => 'Record-Clips',
            'description' => 'Captures notable rounds and highlights during the order so you can keep memorable clips from the run.',
            'icon' => 'assets/addons/record_clips.png',
            'sort_order' => 10,
            'aliases' => ['Record clips', 'Record clips (+25%)', 'Record VOD', 'RECORD CLIPS (+25%)'],
        ],
    ],
];
