<?php

return [
    'rank_order' => [
        'Iron I',
        'Iron II',
        'Iron III',
        'Bronze I',
        'Bronze II',
        'Bronze III',
        'Silver I',
        'Silver II',
        'Silver III',
        'Gold I',
        'Gold II',
        'Gold III',
        'Platinum I',
        'Platinum II',
        'Platinum III',
        'Diamond I',
        'Diamond II',
        'Diamond III',
        'Ascendant I',
        'Ascendant II',
        'Ascendant III',
        'Immortal I',
        'Immortal II',
        'Immortal III',
        'Radiant',
    ],

    'services' => [
        'Rank Boosting' => [
            'kind' => 'rank_boost',
        ],
        'Placement Matches' => [
            'kind' => 'placement_matches',
        ],
        'Ranked Wins' => [
            'kind' => 'ranked_wins',
        ],
        'Radiant Boost' => [
            'kind' => 'radiant_boost',
        ],
    ],

    'base_prices' => [
        'Placement Matches' => [
            'Iron I' => 2.25,
            'Iron II' => 2.25,
            'Iron III' => 2.25,
            'Bronze I' => 3.00,
            'Bronze II' => 3.00,
            'Bronze III' => 3.00,
            'Silver I' => 3.75,
            'Silver II' => 3.75,
            'Silver III' => 3.75,
            'Gold I' => 4.25,
            'Gold II' => 4.25,
            'Gold III' => 4.25,
            'Platinum I' => 4.50,
            'Platinum II' => 4.50,
            'Platinum III' => 4.50,
            'Diamond I' => 5.00,
            'Diamond II' => 5.00,
            'Diamond III' => 5.00,
            'Ascendant I' => 6.50,
            'Ascendant II' => 6.50,
            'Ascendant III' => 6.50,
            'Immortal I' => 9.00,
            'Immortal II' => 11.50,
            'Immortal III' => 16.00,
            'Radiant' => 23.00,
        ],
        'Ranked Wins' => [
            'Iron I' => 3.00,
            'Iron II' => 3.00,
            'Iron III' => 3.00,
            'Bronze I' => 4.00,
            'Bronze II' => 4.00,
            'Bronze III' => 4.00,
            'Silver I' => 5.75,
            'Silver II' => 5.75,
            'Silver III' => 5.75,
            'Gold I' => 6.50,
            'Gold II' => 6.50,
            'Gold III' => 6.50,
            'Platinum I' => 7.00,
            'Platinum II' => 7.00,
            'Platinum III' => 7.00,
            'Diamond I' => 8.50,
            'Diamond II' => 8.50,
            'Diamond III' => 8.50,
            'Ascendant I' => 9.75,
            'Ascendant II' => 9.75,
            'Ascendant III' => 9.75,
            'Immortal I' => 11.00,
            'Immortal II' => 14.75,
            'Immortal III' => 16.00,
            'Radiant' => 26.00,
        ],
        'Rank Boosting' => [
            'Iron I' => 4.50,
            'Iron II' => 4.50,
            'Iron III' => 4.50,
            'Bronze I' => 6.50,
            'Bronze II' => 6.50,
            'Bronze III' => 6.50,
            'Silver I' => 7.50,
            'Silver II' => 7.50,
            'Silver III' => 7.50,
            'Gold I' => 8.50,
            'Gold II' => 8.50,
            'Gold III' => 8.50,
            'Platinum I' => 10.00,
            'Platinum II' => 10.00,
            'Platinum III' => 10.00,
            'Diamond I' => 14.49,
            'Diamond II' => 14.49,
            'Diamond III' => 14.49,
            'Ascendant I' => 17.00,
            'Ascendant II' => 17.00,
            'Ascendant III' => 17.00,
        ],
    ],

    'special_rank_boost_steps' => [
        'Ascendant III->Immortal I' => 39.99,
        'Immortal I->Immortal II' => 79.99,
        'Immortal II->Immortal III' => 97.99,
        'Immortal III->Radiant' => 270.00,
    ],

    'rr_rules' => [
        'current_rr_discount_threshold' => 50,
        'first_step_discount_multiplier' => 0.50,
        'avg_rr_modifiers' => [
            '16' => 1.10,
            '18' => 1.00,
            '20' => 0.95,
        ],
    ],

    'addons' => [
        'Offline Mode' => ['type' => 'free', 'value' => 0],
        'Specific Agents' => ['type' => 'free', 'value' => 0],
        'One-Trick Agent' => ['type' => 'percent', 'value' => 0.20],
        'Solo-Queue Only' => ['type' => 'percent', 'value' => 0.50],
        'No 5-Stack' => ['type' => 'percent', 'value' => 0.15],
        'Streaming' => ['type' => 'percent', 'value' => 0.10],
        'Express Order' => ['type' => 'percent', 'value' => 0.10],
        'Normalize Scores' => ['type' => 'percent', 'value' => 0.20],
        'Record-Clips' => ['type' => 'percent', 'value' => 0.30],
        'Bonus Win' => ['type' => 'bonus_win'],
    ],

    'disabled_addons' => [
        'self_play' => [
            'Offline Mode',
            'Specific Agents',
            'One-Trick Agent',
            'Solo-Queue Only',
            'No 5-Stack',
            'Streaming',
            'Normalize Scores',
            'Record-Clips',
        ],
    ],

    'modifiers' => [
        'region' => [
            'EU' => 1.00,
            'NA' => 1.10,
            'APAC' => 1.05,
            'LATAM' => 0.95,
        ],
        'platform' => [
            'PC' => 1.00,
            'Console' => 1.30,
        ],
        'boost_mode' => [
            'normal' => 1.00,
            'self_play' => 1.95,
        ],
    ],

    'labels' => [
        'boost_modes' => [
            'normal' => 'Account Shared',
            'self_play' => 'Duo / Self-Play',
        ],
        'avg_rr' => [
            '16' => '16 or lower',
            '18' => '18 or lower',
            '20' => '20 or more',
        ],
    ],
];
